apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sqhelp
  name: sqhelp
  namespace: beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqhelp
  template:
    metadata:
      labels:
        app: sqhelp
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: -Djavax.net.ssl.trustStore=/usr/local/https/sqfaas.jks -Djavax.net.ssl.trustStorePassword=demosys
            - name: SERVER_SERVLET_CONTEXTPATH
              value: /help
          image: sinqia.azurecr.io/fundos/sqfaas/sqhelp/sqhelp:1.1.0-rc.1
          imagePullPolicy: Always
          name: sqhelp
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /usr/local/https
              name: sqfaas-files
              readOnly: true
      imagePullSecrets:
        - name: acr-secret
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      volumes:
        - name: sqfaas-files  
          secret:
            secretName: sqfaas-files
