apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - pv.yaml
  - pvc.yaml
  - service.yaml
metadata:
  namespace: env0
