apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mfe-assets-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS, PUT, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type,Authorization,X-Requested-With,x-lockid,Cache-Control,accept-language"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx-private
  tls:
    - hosts:
        - "env1.sqfaas.dev"
      secretName: ingress-secret
  rules:
    - host: "env1.sqfaas.dev"
      http:
        paths:
          - path: /cadastros-basicos/(assets/.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mfe-cadastros-basicos
                port:
                  number: 80
          - path: /gestao-carteiras/(assets/.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mfe-gestao-carteiras
                port:
                  number: 80
          - path: /interoperabilidade/(assets/.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mfe-interoperabilidade
                port:
                  number: 80
          - path: /boletagem/(assets/.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mfe-boletagem
                port:
                  number: 80
          - path: /indices-cotacoes/(assets/.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mfe-indices-cotacoes
                port:
                  number: 80
          - path: /controle-passivo/(assets/.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mfe-controle-passivo
                port:
                  number: 80
          - path: /sqctrl-legado/(assets/.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mfe-sqctrl-legado
                port:
                  number: 80
