apiVersion: v1
kind: ConfigMap
metadata:
  name: svc-param-favoritos-configmap
data:
  SERVER_SERVLET_CONTEXTPATH: /svc-param-favoritos
  SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
  SPRING_DATA_MONGODB_USERNAME: sysdemo
  SPRING_DATA_MONGODB_PASSWORD: demosys
  SPRING_DATA_MONGODB_DATABASE: beta
  SPRING_DATA_MONGODB_HOST: mongodb.database.svc.cluster.local
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: "true"
