apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bff-ingress
  namespace: {{ENV}}
spec:
  ingressClassName: nginx-private
  tls:
    - hosts:
        - "bff.{{ENV}}.sqfaas.dev"
      secretName: ingress-secret
  rules:
    - host: "bff.{{ENV}}.sqfaas.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bff-shell
                port:
                  number: 80
