apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - v9-configmap.yaml
  - v9-deployment.yaml
  - v9-service.yaml
metadata:
  namespace: env0
