apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
  - configmap.yaml
  - deployment.yaml
  - mfe-common-configmap.yaml
  - service.yaml
metadata:
  namespace: env0
